/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        tertiary: "#635b4d",
        "inverse-on-surface": "#f6f0e7",
        secondary: "#705a4f",
        "on-secondary-container": "#766055",
        "surface-variant": "#e7e2d9",
        "surface-tint": "#7f5538",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#4d4639",
        "surface-bright": "#fff9ef",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdbc7",
        "inverse-primary": "#f3bb98",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#201b10",
        "tertiary-fixed": "#ece1cf",
        "on-secondary-fixed": "#281810",
        "error-container": "#ffdad6",
        "surface-container-low": "#f9f3ea",
        "on-secondary-fixed-variant": "#574239",
        "surface-dim": "#dfd9d1",
        outline: "#83746c",
        "primary-container": "#986a4c",
        background: "#fff9ef",
        "surface-container-high": "#ede7df",
        "on-background": "#1d1b16",
        "surface-container-highest": "#e7e2d9",
        "outline-variant": "#d5c3b9",
        "secondary-fixed": "#fbdccf",
        "tertiary-fixed-dim": "#d0c5b4",
        "inverse-surface": "#32302a",
        "primary-fixed-dim": "#f3bb98",
        "secondary-fixed-dim": "#ddc1b3",
        "on-surface": "#1d1b16",
        "on-primary-container": "#fffbff",
        "surface-container": "#f3ede4",
        error: "#ba1a1a",
        "on-surface-variant": "#51443d",
        primary: "#7c5236",
        surface: "#fff9ef",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7c7465",
        "on-primary-fixed-variant": "#643e23",
        "on-primary-fixed": "#311401",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fbdccf",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "stack-sm": "8px",
        "section-gap": "120px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "stack-md": "16px",
        gutter: "16px",
      },
      fontFamily: {
        "title-md": ["Hanken Grotesk"],
        "headline-lg": ["Bodoni Moda"],
        "label-sm": ["Hanken Grotesk"],
        "display-lg": ["Bodoni Moda"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Bodoni Moda"],
        "headline-xl": ["Bodoni Moda"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "300" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.15em", fontWeight: "600" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "300" },
        ],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "300" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
