-- Katalog genisleme: Kadin/Erkek yeni alt kategoriler, Ayakkabi ust kategori ayrimi, Canta genislemesi.
-- Onaylanan urun/kategori listesinden uretildi (bkz. onay artifact'i). Manuel calistirilir.

BEGIN;

-- 1) Yeni kategoriler (CAT-004 Ayakkabi ust kategori dahil)
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-004', 'Ayakkabı', NULL);
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-014', 'Gömlek', 'CAT-001');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-015', 'Bluz', 'CAT-001');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-016', 'Ceket', 'CAT-001');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-017', 'Şort', 'CAT-001');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-018', 'Tişört', 'CAT-001');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-023', 'Gömlek', 'CAT-002');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-024', 'Ceket', 'CAT-002');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-025', 'Takım Elbise', 'CAT-002');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-026', 'Sweatshirt', 'CAT-002');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-027', 'Mont', 'CAT-002');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-041', 'Babet', 'CAT-004');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-042', 'Sneaker', 'CAT-004');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-043', 'Sandalet', 'CAT-004');
INSERT INTO categories (id, name, parent_category_id) VALUES ('CAT-044', 'Topuklu', 'CAT-004');

-- 2) Spor Ayakkabi (PROD-007) yeni Sneaker alt kategorisine tasiniyor
UPDATE products SET category_id = 'CAT-042' WHERE id = 'PROD-007';

-- 3) Eski Ayakkabi kategorisi (Aksesuar altinda) artik kullanilmiyor
DELETE FROM categories WHERE id = 'CAT-032';

-- 4) Yeni urunler (67 adet)
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-008', 'Saten Gömlek', 'Saten kumaş, ofis şıklığı', true, 'CAT-014');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-009', 'Poplin Oversize Gömlek', 'Poplin kumaş, rahat kesim', true, 'CAT-014');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-010', 'Çizgili Keten Gömlek', 'Keten karışım, yazlık', true, 'CAT-014');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-011', 'Uzun Kollu Basic Gömlek', 'Pamuklu, günlük kullanım', true, 'CAT-014');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-012', 'Volanlı Şifon Gömlek', 'Şifon kumaş, volan detay', true, 'CAT-014');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-013', 'Fırfırlı Şifon Bluz', 'Şifon kumaş, fırfır detay', true, 'CAT-015');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-014', 'Kruvaze Saten Bluz', 'Saten kumaş, kruvaze yaka', true, 'CAT-015');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-015', 'Dantel Detaylı Bluz', 'Dantel yaka, günlük şıklık', true, 'CAT-015');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-016', 'Yaka Detaylı Basic Bluz', 'Pamuklu, ofis kullanımı', true, 'CAT-015');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-017', 'Blazer Ceket', 'Astarlı, ofis şıklığı', true, 'CAT-016');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-018', 'Deri Görünümlü Biker Ceket', 'Suni deri, fermuar detay', true, 'CAT-016');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-019', 'Oversize Kot Ceket', 'Denim, rahat kesim', true, 'CAT-016');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-020', 'Yünlü Kaban', 'Yün karışım, kışlık', true, 'CAT-016');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-021', 'Kısa Bomber Ceket', 'Şardonlu, günlük kullanım', true, 'CAT-016');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-022', 'Yüksek Bel Kot Şort', 'Denim, yüksek bel', true, 'CAT-017');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-023', 'Keten Bermuda Şort', 'Keten karışım, yazlık', true, 'CAT-017');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-024', 'Spor Şort', 'Pamuklu, günlük kullanım', true, 'CAT-017');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-025', 'Pileli Kumaş Şort', 'Kumaş, pileli detay', true, 'CAT-017');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-026', 'Basic Crop Tişört', 'Pamuklu, crop kesim', true, 'CAT-018');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-027', 'Baskılı Oversize Tişört', 'Pamuklu, oversize kesim', true, 'CAT-018');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-028', 'Ribana Yaka Tişört', 'Ribana yaka, günlük', true, 'CAT-018');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-029', 'Uzun Kollu Basic Tişört', 'Pamuklu, uzun kol', true, 'CAT-018');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-030', 'Nakışlı Tişört', 'Pamuklu, nakış detay', true, 'CAT-018');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-031', 'Slim Fit Poplin Gömlek', 'Poplin kumaş, slim kesim', true, 'CAT-023');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-032', 'Çizgili Klasik Gömlek', 'Pamuklu, klasik kesim', true, 'CAT-023');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-033', 'Keten Karışımlı Gömlek', 'Keten karışım, yazlık', true, 'CAT-023');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-034', 'Oduncu Kareli Gömlek', 'Flanel, kareli desen', true, 'CAT-023');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-035', 'Denim Gömlek', 'Denim, günlük kullanım', true, 'CAT-023');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-036', 'Blazer Ceket', 'Astarlı, ofis şıklığı', true, 'CAT-024');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-037', 'Kot Ceket', 'Denim, rahat kesim', true, 'CAT-024');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-038', 'Deri Ceket', 'Hakiki deri, biker kesim', true, 'CAT-024');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-039', 'Softshell Outdoor Ceket', 'Su itici, rüzgarlık', true, 'CAT-024');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-040', 'Slim Fit Takım Elbise', 'Yün karışım, slim kesim', true, 'CAT-025');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-041', 'Klasik Kesim Takım Elbise', 'Yün karışım, klasik kesim', true, 'CAT-025');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-042', 'Damat Takım Elbise', 'Saten yaka detaylı, özel gün', true, 'CAT-025');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-043', 'Yünlü Takım Elbise', 'Yün karışım, kışlık', true, 'CAT-025');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-044', 'Kapüşonlu Basic Sweatshirt', 'Şardonlu, günlük kullanım', true, 'CAT-026');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-045', 'Baskılı Sweatshirt', 'Şardonlu, baskı detay', true, 'CAT-026');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-046', 'Şardonlu Sweatshirt', 'Şardonlu, sıcak tutar', true, 'CAT-026');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-047', 'Fermuarlı Sweatshirt', 'Şardonlu, fermuarlı yaka', true, 'CAT-026');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-048', 'Oversize Sweatshirt', 'Şardonlu, oversize kesim', true, 'CAT-026');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-049', 'Şişme Mont', 'Şişme dolgu, kışlık', true, 'CAT-027');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-050', 'Parka Mont', 'Kürk kapüşonlu, kışlık', true, 'CAT-027');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-051', 'Su Geçirmez Outdoor Mont', 'Su geçirmez, outdoor', true, 'CAT-027');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-052', 'Kapüşonlu Kışlık Mont', 'Dolgulu, kapüşonlu', true, 'CAT-027');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-053', 'Klasik Rugan Babet', 'Rugan, günlük şıklık', true, 'CAT-041');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-054', 'Püsküllü Babet', 'Deri görünümlü, püskül detay', true, 'CAT-041');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-055', 'Bantlı Babet', 'Bantlı, günlük kullanım', true, 'CAT-041');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-056', 'Süet Babet', 'Süet, yumuşak taban', true, 'CAT-041');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-057', 'Toka Detaylı Babet', 'Toka detaylı, günlük', true, 'CAT-041');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-058', 'Örgü Sneaker', 'Örgü kumaş, hafif taban', true, 'CAT-042');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-059', 'Retro Sneaker', 'Deri görünümlü, retro model', true, 'CAT-042');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-060', 'Platform Sneaker', 'Platform taban, günlük', true, 'CAT-042');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-061', 'Deri Sneaker', 'Hakiki deri, klasik model', true, 'CAT-042');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-062', 'Yazlık Deri Sandalet', 'Hakiki deri, yazlık', true, 'CAT-043');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-063', 'Bantlı Düz Sandalet', 'Bantlı, düz taban', true, 'CAT-043');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-064', 'Dolgu Topuklu Sandalet', 'Dolgu topuk, yazlık', true, 'CAT-043');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-065', 'Parmak Arası Sandalet', 'Hafif, günlük kullanım', true, 'CAT-043');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-066', 'Stiletto Topuklu Ayakkabı', 'İnce topuk, özel gün', true, 'CAT-044');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-067', 'Bantlı Topuklu Ayakkabı', 'Bantlı, orta topuk', true, 'CAT-044');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-068', 'Platform Topuklu Ayakkabı', 'Platform taban, konforlu', true, 'CAT-044');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-069', 'Süet Topuklu Ayakkabı', 'Süet, şık kesim', true, 'CAT-044');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-070', 'Rugan Topuklu Ayakkabı', 'Rugan, özel gün', true, 'CAT-044');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-071', 'Askılı Omuz Çantası', 'Suni deri, günlük kullanım', true, 'CAT-031');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-072', 'Sırt Çantası', 'Su geçirmez kumaş, günlük', true, 'CAT-031');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-073', 'El Çantası', 'Hakiki deri, şık kesim', true, 'CAT-031');
INSERT INTO products (id, name, description, is_active, category_id) VALUES ('PROD-074', 'Clutch Abiye Çanta', 'Simli kumaş, özel gün', true, 'CAT-031');

-- 5) Yeni fiyatlar (67 adet)
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-008', 'PROD-008', 449.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-009', 'PROD-009', 399.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-010', 'PROD-010', 479.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-011', 'PROD-011', 329.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-012', 'PROD-012', 549.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-013', 'PROD-013', 329.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-014', 'PROD-014', 379.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-015', 'PROD-015', 419.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-016', 'PROD-016', 259.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-017', 'PROD-017', 1199.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-018', 'PROD-018', 1349.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-019', 'PROD-019', 899.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-020', 'PROD-020', 1499.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-021', 'PROD-021', 949.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-022', 'PROD-022', 279.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-023', 'PROD-023', 249.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-024', 'PROD-024', 199.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-025', 'PROD-025', 329.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-026', 'PROD-026', 199.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-027', 'PROD-027', 249.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-028', 'PROD-028', 179.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-029', 'PROD-029', 229.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-030', 'PROD-030', 269.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-031', 'PROD-031', 449.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-032', 'PROD-032', 399.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-033', 'PROD-033', 479.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-034', 'PROD-034', 429.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-035', 'PROD-035', 459.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-036', 'PROD-036', 1299.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-037', 'PROD-037', 899.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-038', 'PROD-038', 1599.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-039', 'PROD-039', 1099.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-040', 'PROD-040', 2999.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-041', 'PROD-041', 2699.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-042', 'PROD-042', 3799.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-043', 'PROD-043', 3299.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-044', 'PROD-044', 399.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-045', 'PROD-045', 349.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-046', 'PROD-046', 429.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-047', 'PROD-047', 459.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-048', 'PROD-048', 379.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-049', 'PROD-049', 1299.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-050', 'PROD-050', 1599.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-051', 'PROD-051', 1799.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-052', 'PROD-052', 1449.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-053', 'PROD-053', 449.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-054', 'PROD-054', 399.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-055', 'PROD-055', 429.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-056', 'PROD-056', 479.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-057', 'PROD-057', 459.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-058', 'PROD-058', 599.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-059', 'PROD-059', 749.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-060', 'PROD-060', 679.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-061', 'PROD-061', 899.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-062', 'PROD-062', 349.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-063', 'PROD-063', 299.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-064', 'PROD-064', 399.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-065', 'PROD-065', 249.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-066', 'PROD-066', 599.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-067', 'PROD-067', 549.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-068', 'PROD-068', 649.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-069', 'PROD-069', 699.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-070', 'PROD-070', 579.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-071', 'PROD-071', 649.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-072', 'PROD-072', 549.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-073', 'PROD-073', 749.90, now(), true);
INSERT INTO prices (id, product_id, amount, valid_from, is_active) VALUES ('PRICE-PROD-074', 'PROD-074', 399.90, now(), true);

-- 6) Yeni varyantlar (374 adet)
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-015', 'PROD-008', 'S', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-016', 'PROD-008', 'M', 'Beyaz', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-017', 'PROD-008', 'L', 'Beyaz', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-018', 'PROD-008', 'S', 'Ekru', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-019', 'PROD-008', 'M', 'Ekru', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-020', 'PROD-008', 'L', 'Ekru', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-021', 'PROD-009', 'S', 'Mavi', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-022', 'PROD-009', 'M', 'Mavi', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-023', 'PROD-009', 'L', 'Mavi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-024', 'PROD-009', 'S', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-025', 'PROD-009', 'M', 'Beyaz', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-026', 'PROD-009', 'L', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-027', 'PROD-010', 'S', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-028', 'PROD-010', 'M', 'Lacivert', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-029', 'PROD-010', 'S', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-030', 'PROD-010', 'M', 'Beyaz', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-031', 'PROD-011', 'S', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-032', 'PROD-011', 'M', 'Siyah', 18);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-033', 'PROD-011', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-034', 'PROD-011', 'S', 'Beyaz', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-035', 'PROD-011', 'M', 'Beyaz', 20);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-036', 'PROD-011', 'L', 'Beyaz', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-037', 'PROD-011', 'S', 'Pudra', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-038', 'PROD-011', 'M', 'Pudra', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-039', 'PROD-011', 'L', 'Pudra', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-040', 'PROD-012', 'S', 'Krem', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-041', 'PROD-012', 'M', 'Krem', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-042', 'PROD-012', 'S', 'Yeşil', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-043', 'PROD-012', 'M', 'Yeşil', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-044', 'PROD-013', 'S', 'Beyaz', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-045', 'PROD-013', 'M', 'Beyaz', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-046', 'PROD-013', 'L', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-047', 'PROD-013', 'S', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-048', 'PROD-013', 'M', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-049', 'PROD-013', 'L', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-050', 'PROD-014', 'S', 'Bordo', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-051', 'PROD-014', 'M', 'Bordo', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-052', 'PROD-014', 'S', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-053', 'PROD-014', 'M', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-054', 'PROD-015', 'S', 'Ekru', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-055', 'PROD-015', 'M', 'Ekru', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-056', 'PROD-015', 'L', 'Ekru', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-057', 'PROD-015', 'S', 'Pudra', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-058', 'PROD-015', 'M', 'Pudra', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-059', 'PROD-015', 'L', 'Pudra', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-060', 'PROD-016', 'S', 'Beyaz', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-061', 'PROD-016', 'M', 'Beyaz', 19);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-062', 'PROD-016', 'L', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-063', 'PROD-016', 'S', 'Lacivert', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-064', 'PROD-016', 'M', 'Lacivert', 17);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-065', 'PROD-016', 'L', 'Lacivert', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-066', 'PROD-017', 'S', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-067', 'PROD-017', 'M', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-068', 'PROD-017', 'L', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-069', 'PROD-017', 'S', 'Bej', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-070', 'PROD-017', 'M', 'Bej', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-071', 'PROD-017', 'L', 'Bej', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-072', 'PROD-018', 'S', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-073', 'PROD-018', 'M', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-074', 'PROD-018', 'S', 'Bordo', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-075', 'PROD-018', 'M', 'Bordo', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-076', 'PROD-019', 'S', 'Mavi', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-077', 'PROD-019', 'M', 'Mavi', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-078', 'PROD-019', 'L', 'Mavi', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-079', 'PROD-019', 'S', 'Açık Mavi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-080', 'PROD-019', 'M', 'Açık Mavi', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-081', 'PROD-019', 'L', 'Açık Mavi', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-082', 'PROD-020', 'S', 'Kamel', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-083', 'PROD-020', 'M', 'Kamel', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-084', 'PROD-020', 'L', 'Kamel', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-085', 'PROD-020', 'S', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-086', 'PROD-020', 'M', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-087', 'PROD-020', 'L', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-088', 'PROD-021', 'S', 'Haki', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-089', 'PROD-021', 'M', 'Haki', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-090', 'PROD-021', 'S', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-091', 'PROD-021', 'M', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-092', 'PROD-022', '36', 'Mavi', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-093', 'PROD-022', '38', 'Mavi', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-094', 'PROD-022', '40', 'Mavi', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-095', 'PROD-022', '36', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-096', 'PROD-022', '38', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-097', 'PROD-022', '40', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-098', 'PROD-023', 'S', 'Bej', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-099', 'PROD-023', 'M', 'Bej', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-100', 'PROD-023', 'L', 'Bej', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-101', 'PROD-023', 'S', 'Beyaz', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-102', 'PROD-023', 'M', 'Beyaz', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-103', 'PROD-023', 'L', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-104', 'PROD-024', 'S', 'Siyah', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-105', 'PROD-024', 'M', 'Siyah', 20);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-106', 'PROD-024', 'L', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-107', 'PROD-024', 'S', 'Gri', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-108', 'PROD-024', 'M', 'Gri', 18);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-109', 'PROD-024', 'L', 'Gri', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-110', 'PROD-025', 'S', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-111', 'PROD-025', 'M', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-112', 'PROD-025', 'S', 'Haki', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-113', 'PROD-025', 'M', 'Haki', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-114', 'PROD-026', 'S', 'Beyaz', 18);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-115', 'PROD-026', 'M', 'Beyaz', 22);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-116', 'PROD-026', 'L', 'Beyaz', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-117', 'PROD-026', 'S', 'Siyah', 20);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-118', 'PROD-026', 'M', 'Siyah', 24);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-119', 'PROD-026', 'L', 'Siyah', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-120', 'PROD-026', 'S', 'Pudra', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-121', 'PROD-026', 'M', 'Pudra', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-122', 'PROD-026', 'L', 'Pudra', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-123', 'PROD-027', 'S', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-124', 'PROD-027', 'M', 'Beyaz', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-125', 'PROD-027', 'L', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-126', 'PROD-027', 'S', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-127', 'PROD-027', 'M', 'Siyah', 17);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-128', 'PROD-027', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-129', 'PROD-028', 'S', 'Beyaz', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-130', 'PROD-028', 'M', 'Beyaz', 18);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-131', 'PROD-028', 'S', 'Lacivert', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-132', 'PROD-028', 'M', 'Lacivert', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-133', 'PROD-028', 'S', 'Bordo', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-134', 'PROD-028', 'M', 'Bordo', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-135', 'PROD-029', 'S', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-136', 'PROD-029', 'M', 'Siyah', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-137', 'PROD-029', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-138', 'PROD-029', 'S', 'Gri', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-139', 'PROD-029', 'M', 'Gri', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-140', 'PROD-029', 'L', 'Gri', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-141', 'PROD-030', 'S', 'Ekru', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-142', 'PROD-030', 'M', 'Ekru', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-143', 'PROD-030', 'S', 'Yeşil', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-144', 'PROD-030', 'M', 'Yeşil', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-145', 'PROD-031', 'S', 'Beyaz', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-146', 'PROD-031', 'M', 'Beyaz', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-147', 'PROD-031', 'L', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-148', 'PROD-031', 'S', 'Lacivert', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-149', 'PROD-031', 'M', 'Lacivert', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-150', 'PROD-031', 'L', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-151', 'PROD-032', 'M', 'Mavi', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-152', 'PROD-032', 'L', 'Mavi', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-153', 'PROD-032', 'XL', 'Mavi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-154', 'PROD-032', 'M', 'Beyaz', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-155', 'PROD-032', 'L', 'Beyaz', 17);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-156', 'PROD-032', 'XL', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-157', 'PROD-033', 'S', 'Bej', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-158', 'PROD-033', 'M', 'Bej', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-159', 'PROD-033', 'L', 'Bej', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-160', 'PROD-033', 'S', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-161', 'PROD-033', 'M', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-162', 'PROD-033', 'L', 'Beyaz', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-163', 'PROD-034', 'M', 'Kırmızı', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-164', 'PROD-034', 'L', 'Kırmızı', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-165', 'PROD-034', 'XL', 'Kırmızı', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-166', 'PROD-034', 'M', 'Yeşil', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-167', 'PROD-034', 'L', 'Yeşil', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-168', 'PROD-034', 'XL', 'Yeşil', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-169', 'PROD-035', 'S', 'Mavi', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-170', 'PROD-035', 'M', 'Mavi', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-171', 'PROD-035', 'L', 'Mavi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-172', 'PROD-035', 'S', 'Lacivert', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-173', 'PROD-035', 'M', 'Lacivert', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-174', 'PROD-035', 'L', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-175', 'PROD-036', 'M', 'Lacivert', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-176', 'PROD-036', 'L', 'Lacivert', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-177', 'PROD-036', 'XL', 'Lacivert', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-178', 'PROD-036', 'M', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-179', 'PROD-036', 'L', 'Siyah', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-180', 'PROD-036', 'XL', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-181', 'PROD-037', 'S', 'Mavi', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-182', 'PROD-037', 'M', 'Mavi', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-183', 'PROD-037', 'L', 'Mavi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-184', 'PROD-037', 'S', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-185', 'PROD-037', 'M', 'Siyah', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-186', 'PROD-037', 'L', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-187', 'PROD-038', 'M', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-188', 'PROD-038', 'L', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-189', 'PROD-038', 'M', 'Kahverengi', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-190', 'PROD-038', 'L', 'Kahverengi', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-191', 'PROD-039', 'M', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-192', 'PROD-039', 'L', 'Siyah', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-193', 'PROD-039', 'XL', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-194', 'PROD-039', 'M', 'Haki', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-195', 'PROD-039', 'L', 'Haki', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-196', 'PROD-039', 'XL', 'Haki', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-197', 'PROD-040', '48', 'Lacivert', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-198', 'PROD-040', '50', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-199', 'PROD-040', '52', 'Lacivert', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-200', 'PROD-040', '48', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-201', 'PROD-040', '50', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-202', 'PROD-040', '52', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-203', 'PROD-041', '50', 'Antrasit', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-204', 'PROD-041', '52', 'Antrasit', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-205', 'PROD-041', '54', 'Antrasit', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-206', 'PROD-041', '50', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-207', 'PROD-041', '52', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-208', 'PROD-041', '54', 'Siyah', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-209', 'PROD-042', '48', 'Siyah', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-210', 'PROD-042', '50', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-211', 'PROD-042', '52', 'Siyah', 2);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-212', 'PROD-042', '48', 'Lacivert', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-213', 'PROD-042', '50', 'Lacivert', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-214', 'PROD-042', '52', 'Lacivert', 2);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-215', 'PROD-043', '50', 'Gri', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-216', 'PROD-043', '52', 'Gri', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-217', 'PROD-043', '50', 'Antrasit', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-218', 'PROD-043', '52', 'Antrasit', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-219', 'PROD-044', 'S', 'Gri', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-220', 'PROD-044', 'M', 'Gri', 19);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-221', 'PROD-044', 'L', 'Gri', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-222', 'PROD-044', 'S', 'Siyah', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-223', 'PROD-044', 'M', 'Siyah', 21);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-224', 'PROD-044', 'L', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-225', 'PROD-045', 'M', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-226', 'PROD-045', 'L', 'Siyah', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-227', 'PROD-045', 'XL', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-228', 'PROD-045', 'M', 'Lacivert', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-229', 'PROD-045', 'L', 'Lacivert', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-230', 'PROD-045', 'XL', 'Lacivert', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-231', 'PROD-046', 'S', 'Bordo', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-232', 'PROD-046', 'M', 'Bordo', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-233', 'PROD-046', 'L', 'Bordo', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-234', 'PROD-046', 'S', 'Gri', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-235', 'PROD-046', 'M', 'Gri', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-236', 'PROD-046', 'L', 'Gri', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-237', 'PROD-047', 'M', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-238', 'PROD-047', 'L', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-239', 'PROD-047', 'XL', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-240', 'PROD-047', 'M', 'Haki', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-241', 'PROD-047', 'L', 'Haki', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-242', 'PROD-047', 'XL', 'Haki', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-243', 'PROD-048', 'S', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-244', 'PROD-048', 'M', 'Beyaz', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-245', 'PROD-048', 'L', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-246', 'PROD-048', 'S', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-247', 'PROD-048', 'M', 'Siyah', 17);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-248', 'PROD-048', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-249', 'PROD-049', 'M', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-250', 'PROD-049', 'L', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-251', 'PROD-049', 'XL', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-252', 'PROD-049', 'M', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-253', 'PROD-049', 'L', 'Lacivert', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-254', 'PROD-049', 'XL', 'Lacivert', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-255', 'PROD-050', 'M', 'Haki', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-256', 'PROD-050', 'L', 'Haki', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-257', 'PROD-050', 'XL', 'Haki', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-258', 'PROD-050', 'M', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-259', 'PROD-050', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-260', 'PROD-050', 'XL', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-261', 'PROD-051', 'M', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-262', 'PROD-051', 'L', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-263', 'PROD-051', 'XL', 'Siyah', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-264', 'PROD-051', 'M', 'Gri', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-265', 'PROD-051', 'L', 'Gri', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-266', 'PROD-051', 'XL', 'Gri', 2);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-267', 'PROD-052', 'M', 'Lacivert', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-268', 'PROD-052', 'L', 'Lacivert', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-269', 'PROD-052', 'M', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-270', 'PROD-052', 'L', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-271', 'PROD-053', '36', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-272', 'PROD-053', '37', 'Siyah', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-273', 'PROD-053', '38', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-274', 'PROD-053', '36', 'Nude', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-275', 'PROD-053', '37', 'Nude', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-276', 'PROD-053', '38', 'Nude', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-277', 'PROD-054', '36', 'Kahverengi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-278', 'PROD-054', '37', 'Kahverengi', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-279', 'PROD-054', '38', 'Kahverengi', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-280', 'PROD-054', '36', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-281', 'PROD-054', '37', 'Siyah', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-282', 'PROD-054', '38', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-283', 'PROD-055', '37', 'Nude', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-284', 'PROD-055', '38', 'Nude', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-285', 'PROD-055', '39', 'Nude', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-286', 'PROD-055', '37', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-287', 'PROD-055', '38', 'Beyaz', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-288', 'PROD-055', '39', 'Beyaz', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-289', 'PROD-056', '37', 'Bej', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-290', 'PROD-056', '38', 'Bej', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-291', 'PROD-056', '39', 'Bej', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-292', 'PROD-056', '37', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-293', 'PROD-056', '38', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-294', 'PROD-056', '39', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-295', 'PROD-057', '36', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-296', 'PROD-057', '37', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-297', 'PROD-057', '38', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-298', 'PROD-057', '36', 'Kırmızı', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-299', 'PROD-057', '37', 'Kırmızı', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-300', 'PROD-057', '38', 'Kırmızı', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-301', 'PROD-058', '39', 'Beyaz', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-302', 'PROD-058', '40', 'Beyaz', 15);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-303', 'PROD-058', '41', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-304', 'PROD-058', '39', 'Gri', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-305', 'PROD-058', '40', 'Gri', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-306', 'PROD-058', '41', 'Gri', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-307', 'PROD-059', '40', 'Beyaz', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-308', 'PROD-059', '41', 'Beyaz', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-309', 'PROD-059', '42', 'Beyaz', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-310', 'PROD-059', '40', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-311', 'PROD-059', '41', 'Siyah', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-312', 'PROD-059', '42', 'Siyah', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-313', 'PROD-060', '36', 'Beyaz', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-314', 'PROD-060', '37', 'Beyaz', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-315', 'PROD-060', '38', 'Beyaz', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-316', 'PROD-060', '36', 'Pembe', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-317', 'PROD-060', '37', 'Pembe', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-318', 'PROD-060', '38', 'Pembe', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-319', 'PROD-061', '40', 'Beyaz', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-320', 'PROD-061', '41', 'Beyaz', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-321', 'PROD-061', '42', 'Beyaz', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-322', 'PROD-061', '40', 'Lacivert', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-323', 'PROD-061', '41', 'Lacivert', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-324', 'PROD-061', '42', 'Lacivert', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-325', 'PROD-062', '36', 'Kahverengi', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-326', 'PROD-062', '37', 'Kahverengi', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-327', 'PROD-062', '38', 'Kahverengi', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-328', 'PROD-062', '36', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-329', 'PROD-062', '37', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-330', 'PROD-062', '38', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-331', 'PROD-063', '37', 'Bej', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-332', 'PROD-063', '38', 'Bej', 14);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-333', 'PROD-063', '39', 'Bej', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-334', 'PROD-063', '37', 'Beyaz', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-335', 'PROD-063', '38', 'Beyaz', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-336', 'PROD-063', '39', 'Beyaz', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-337', 'PROD-064', '36', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-338', 'PROD-064', '37', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-339', 'PROD-064', '38', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-340', 'PROD-064', '36', 'Nude', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-341', 'PROD-064', '37', 'Nude', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-342', 'PROD-064', '38', 'Nude', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-343', 'PROD-065', '37', 'Kahverengi', 12);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-344', 'PROD-065', '38', 'Kahverengi', 16);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-345', 'PROD-065', '39', 'Kahverengi', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-346', 'PROD-065', '37', 'Siyah', 13);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-347', 'PROD-065', '38', 'Siyah', 17);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-348', 'PROD-065', '39', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-349', 'PROD-066', '36', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-350', 'PROD-066', '37', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-351', 'PROD-066', '38', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-352', 'PROD-066', '36', 'Nude', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-353', 'PROD-066', '37', 'Nude', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-354', 'PROD-066', '38', 'Nude', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-355', 'PROD-067', '37', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-356', 'PROD-067', '38', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-357', 'PROD-067', '39', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-358', 'PROD-067', '37', 'Kırmızı', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-359', 'PROD-067', '38', 'Kırmızı', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-360', 'PROD-067', '39', 'Kırmızı', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-361', 'PROD-068', '36', 'Bej', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-362', 'PROD-068', '37', 'Bej', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-363', 'PROD-068', '38', 'Bej', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-364', 'PROD-068', '36', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-365', 'PROD-068', '37', 'Siyah', 10);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-366', 'PROD-068', '38', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-367', 'PROD-069', '37', 'Bordo', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-368', 'PROD-069', '38', 'Bordo', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-369', 'PROD-069', '39', 'Bordo', 3);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-370', 'PROD-069', '37', 'Siyah', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-371', 'PROD-069', '38', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-372', 'PROD-069', '39', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-373', 'PROD-070', '36', 'Siyah', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-374', 'PROD-070', '37', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-375', 'PROD-070', '38', 'Siyah', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-376', 'PROD-070', '36', 'Nude', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-377', 'PROD-070', '37', 'Nude', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-378', 'PROD-070', '38', 'Nude', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-379', 'PROD-071', 'Standart', 'Siyah', 9);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-380', 'PROD-071', 'Standart', 'Kahverengi', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-381', 'PROD-071', 'Standart', 'Kırmızı', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-382', 'PROD-072', 'Standart', 'Siyah', 11);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-383', 'PROD-072', 'Standart', 'Lacivert', 8);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-384', 'PROD-073', 'Standart', 'Siyah', 7);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-385', 'PROD-073', 'Standart', 'Bej', 5);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-386', 'PROD-073', 'Standart', 'Nude', 4);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-387', 'PROD-074', 'Standart', 'Gümüş', 6);
INSERT INTO product_variants (id, product_id, size, color, stock_quantity) VALUES ('VAR-388', 'PROD-074', 'Standart', 'Siyah', 8);

COMMIT;
